[package]
name = "cities"
version.workspace = true
edition.workspace = true

[dependencies]
clap.workspace = true
serde.workspace = true
smol_str.workspace = true
bitflags.workspace = true
shapefile.workspace = true
bevy_common_assets.workspace = true
ron.workspace = true
thiserror.workspace = true
terrain.workspace = true
bevy = { workspace = true, features = ["bevy_asset"] }
