[package]
name = "airplanes"
version.workspace = true
edition.workspace = true

[dependencies]
terrain.workspace = true
big_space.workspace = true
bevy.workspace = true
bytemuck.workspace = true

buildings.workspace = true
cities.workspace = true
workspace.workspace = true

[dev-dependencies]
bevy-inspector-egui.workspace = true
bevy = { workspace = true, features = ["bevy_dev_tools"] }
ron.workspace = true
naga = { version = "=29.0.4", features = ["wgsl-in"] }
