[package]
name = "scenario"
version.workspace = true
edition.workspace = true

[dependencies]
bevy.workspace = true
serde.workspace = true
smol_str.workspace = true
big_space.workspace = true
bevy_common_assets.workspace = true

earth.workspace = true
cities.workspace = true
terrain.workspace = true
