[package]
name = "labels"
version.workspace = true
edition.workspace = true

[dependencies]
bevy = { workspace = true, features = ["bevy_feathers", "bevy_scene", "bevy_state"] }

cities.workspace = true
terrain.workspace = true

[dev-dependencies]
workspace.workspace = true
big_space.workspace = true
scenario.workspace = true
bevy-inspector-egui.workspace = true
bevy = { workspace = true, default-features = true, features = ["bevy_dev_tools", "bevy_feathers"] }
