[package]
name = "terrain"
version.workspace = true
edition.workspace = true

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ["cfg(feature, values(\"webgpu\"))"] }

[dependencies]
ron.workspace = true
bevy = { workspace = true, features = ["bevy_render", "bevy_asset", "bevy_log", "bevy_pbr","bevy_core_pipeline", "bevy_gizmos"] }
smol_str.workspace = true
bevy_common_assets.workspace = true
big_space.workspace = true
tiff.workspace = true
bytemuck.workspace = true
ndarray.workspace = true
itertools.workspace = true
bitflags.workspace = true
serde.workspace = true
async-channel.workspace = true
indexmap.workspace = true
slab.workspace = true

[dev-dependencies]
workspace.workspace = true
bevy-inspector-egui.workspace = true
bevy = { workspace = true, default-features = true, features = ["bevy_dev_tools"] }

[[example]]
name = "terrain"
path = "example/main.rs"
