[package]
name = "shipping"
version.workspace = true
edition.workspace = true

[dependencies]
terrain.workspace = true
big_space.workspace = true
bevy.workspace = true
bytemuck.workspace = true

shipping-lanes.workspace = true
workspace.workspace = true

[dev-dependencies]
bevy-inspector-egui.workspace = true
bevy = { workspace = true, features = ["bevy_dev_tools"] }
